-- Phase 1 Plan 02: Initial schema migration
-- Tables: user_profiles + integrations
-- Generated by: npx drizzle-kit generate (drizzle-orm@0.45.2)
-- Copied to supabase/migrations/ and applied via: npx supabase db push
-- DO NOT run drizzle-kit migrate against Supabase (RESEARCH.md Pitfall 2)
--
-- Deviations from raw drizzle-kit output:
--   - Added FK REFERENCES auth.users(id) ON DELETE CASCADE on both tables
--     (Drizzle cannot cross schemas; FKs added manually per DATA-FLOW §2.1 and §2.2)

CREATE TABLE IF NOT EXISTS "integrations" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
	"provider" text NOT NULL,
	"status" text NOT NULL,
	"access_token_encrypted" text NOT NULL,
	"refresh_token_encrypted" text,
	"scopes" text[] NOT NULL,
	"provider_account_id" text,
	"last_synced_at" timestamp with time zone,
	"last_error" text,
	"connected_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone,
	CONSTRAINT "integrations_user_provider_unique" UNIQUE("user_id","provider")
);

CREATE TABLE IF NOT EXISTS "user_profiles" (
	"user_id" uuid PRIMARY KEY NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
	"display_name" text,
	"avatar_url" text,
	"shopify_shop" text,
	"onboarding_completed_at" timestamp with time zone,
	"deletion_requested_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "integrations" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "user_profiles" ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS "idx_integrations_user_provider" ON "integrations" USING btree ("user_id","provider");

CREATE POLICY "integrations_user_policy" ON "integrations" AS PERMISSIVE FOR ALL TO "authenticated" USING ((SELECT auth.uid()) = "integrations"."user_id") WITH CHECK ((SELECT auth.uid()) = "integrations"."user_id");

CREATE POLICY "user_profiles_user_policy" ON "user_profiles" AS PERMISSIVE FOR ALL TO "authenticated" USING ((SELECT auth.uid()) = "user_profiles"."user_id") WITH CHECK ((SELECT auth.uid()) = "user_profiles"."user_id");
