-- Phase 2 Plan 02: Phase 2 tables migration
-- Tables: workflows, workflow_versions, workflow_runs, activity_entries, approvals,
--         threads, messages, memory_items, memory_embeddings, brand_voice_profiles,
--         brand_voice_samples, autonomy_thresholds, shopify_products,
--         shopify_product_variants, shopify_orders, shopify_pages, shopify_redirects,
--         shopify_sync_state, gmail_threads, gmail_messages, gmail_sync_state,
--         agent_telemetry, cost_aggregates
--         (+ ALTER TABLE user_profiles ADD COLUMN onboarding_step)
-- Generated by: hand-authored from Drizzle schemas (drizzle-kit generate then adapted)
-- Applied via: npx supabase db push
-- DO NOT run drizzle-kit migrate against Supabase (RESEARCH.md Pitfall 2)
--
-- Cross-schema FKs to auth.users added manually (Drizzle cannot cross schemas)
-- update_updated_at_column() trigger function ALREADY EXISTS from migration 0002 — reused, not redefined

-- ─── pgvector extension (MUST be first) ──────────────────────────────────────

CREATE EXTENSION IF NOT EXISTS vector;

-- ─── workflows ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "workflows" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "name" text NOT NULL,
    "description" text,
    "automation_level" text NOT NULL DEFAULT 'L2',
    "status" text NOT NULL DEFAULT 'draft',
    "trigger_type" text NOT NULL,
    "trigger_config" jsonb NOT NULL DEFAULT '{}',
    "current_version_id" uuid,
    "source" text NOT NULL DEFAULT 'chat',
    "source_reference_id" uuid,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "workflows" ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS "idx_workflows_user_status" ON "workflows" USING btree ("user_id", "status");

CREATE POLICY "workflows_user_policy" ON "workflows"
    AS PERMISSIVE FOR ALL TO "authenticated"
    USING ((SELECT auth.uid()) = "workflows"."user_id")
    WITH CHECK ((SELECT auth.uid()) = "workflows"."user_id");

CREATE TRIGGER workflows_updated_at
    BEFORE UPDATE ON "workflows"
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE "workflows"
    ADD CONSTRAINT workflows_automation_level_check
        CHECK (automation_level IN ('L1', 'L2', 'L3')),
    ADD CONSTRAINT workflows_status_check
        CHECK (status IN ('active', 'paused', 'draft', 'archived'));

-- ─── workflow_versions ────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "workflow_versions" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
    "workflow_id" uuid NOT NULL REFERENCES "workflows"(id) ON DELETE CASCADE,
    "version_number" integer NOT NULL,
    "definition" jsonb NOT NULL,
    "schema_version" integer NOT NULL DEFAULT 1,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "created_by_thread_id" uuid,
    CONSTRAINT "workflow_versions_workflow_version_unique" UNIQUE ("workflow_id", "version_number")
);

CREATE INDEX IF NOT EXISTS "idx_workflow_versions_workflow" ON "workflow_versions" USING btree ("workflow_id");

-- Add deferred FK: workflows.current_version_id → workflow_versions.id
-- (FK declared after workflow_versions table exists to resolve circular dependency)
ALTER TABLE "workflows"
    ADD CONSTRAINT "workflows_current_version_id_fk"
    FOREIGN KEY ("current_version_id") REFERENCES "workflow_versions"(id)
    DEFERRABLE INITIALLY DEFERRED;

-- ─── workflow_runs ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "workflow_runs" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "workflow_id" uuid NOT NULL REFERENCES "workflows"(id) ON DELETE CASCADE,
    "workflow_version_id" uuid NOT NULL REFERENCES "workflow_versions"(id),
    "workflow_version_snapshot" jsonb NOT NULL,
    "trigger_source" text NOT NULL,
    "status" text NOT NULL,
    "current_step_id" text,
    "inngest_function_id" text,
    "error_summary" text,
    "metadata" jsonb DEFAULT '{}',
    "started_at" timestamp with time zone DEFAULT now() NOT NULL,
    "completed_at" timestamp with time zone
);

ALTER TABLE "workflow_runs" ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS "idx_workflow_runs_user_workflow" ON "workflow_runs" USING btree ("user_id", "workflow_id", "started_at" DESC);
CREATE INDEX IF NOT EXISTS "idx_workflow_runs_status" ON "workflow_runs" USING btree ("status") WHERE status IN ('queued', 'running', 'paused_for_approval', 'paused_manual');

CREATE POLICY "workflow_runs_user_policy" ON "workflow_runs"
    AS PERMISSIVE FOR ALL TO "authenticated"
    USING ((SELECT auth.uid()) = "workflow_runs"."user_id")
    WITH CHECK ((SELECT auth.uid()) = "workflow_runs"."user_id");

ALTER TABLE "workflow_runs"
    ADD CONSTRAINT workflow_runs_status_check
        CHECK (status IN ('queued', 'running', 'paused_for_approval', 'paused_manual', 'succeeded', 'failed', 'expired'));

-- ─── threads ──────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "threads" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "title" text,
    "agent_context" text NOT NULL DEFAULT 'orchestrator',
    "context_workflow_id" uuid REFERENCES "workflows"(id),
    "last_message_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "archived_at" timestamp with time zone
);

ALTER TABLE "threads" ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS "idx_threads_user_last" ON "threads" USING btree ("user_id", "last_message_at" DESC NULLS LAST) WHERE archived_at IS NULL;

CREATE POLICY "threads_user_policy" ON "threads"
    AS PERMISSIVE FOR ALL TO "authenticated"
    USING ((SELECT auth.uid()) = "threads"."user_id")
    WITH CHECK ((SELECT auth.uid()) = "threads"."user_id");

-- ─── messages ─────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "messages" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
    "thread_id" uuid NOT NULL REFERENCES "threads"(id) ON DELETE CASCADE,
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "role" text NOT NULL,
    "content" text,
    "tool_calls" jsonb,
    "tool_call_id" text,
    "inline_block_type" text,
    "inline_block_payload" jsonb,
    "status" text NOT NULL DEFAULT 'complete',
    "model_id" text,
    "token_input" integer,
    "token_output" integer,
    "latency_ms" integer,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "messages" ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS "idx_messages_thread_time" ON "messages" USING btree ("thread_id", "created_at");

CREATE POLICY "messages_user_policy" ON "messages"
    AS PERMISSIVE FOR ALL TO "authenticated"
    USING ((SELECT auth.uid()) = "messages"."user_id")
    WITH CHECK ((SELECT auth.uid()) = "messages"."user_id");

-- ─── approvals ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "approvals" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "workflow_run_id" uuid REFERENCES "workflow_runs"(id),
    "thread_id" uuid REFERENCES "threads"(id),
    "message_id" uuid REFERENCES "messages"(id),
    "status" text NOT NULL DEFAULT 'pending',
    "action_type" text NOT NULL,
    "action_summary" text NOT NULL,
    "stakes" text NOT NULL,
    "preview" jsonb NOT NULL,
    "reasoning_summary" text NOT NULL,
    "reasoning_chain" jsonb,
    "downstream_impact" text,
    "estimated_review_seconds" integer,
    "proposed_action" jsonb NOT NULL,
    "inngest_event_key" text,
    "snoozed_until" timestamp with time zone,
    "expires_at" timestamp with time zone NOT NULL,
    "resolved_at" timestamp with time zone,
    "resolved_by_path" text,
    "reject_reason" text,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "approvals" ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS "idx_approvals_user_pending" ON "approvals" USING btree ("user_id", "status", "created_at" DESC) WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS "idx_approvals_thread" ON "approvals" USING btree ("thread_id") WHERE thread_id IS NOT NULL;

CREATE POLICY "approvals_user_policy" ON "approvals"
    AS PERMISSIVE FOR ALL TO "authenticated"
    USING ((SELECT auth.uid()) = "approvals"."user_id")
    WITH CHECK ((SELECT auth.uid()) = "approvals"."user_id");

ALTER TABLE "approvals"
    ADD CONSTRAINT approvals_status_check
        CHECK (status IN ('pending', 'approved', 'rejected', 'snoozed', 'expired'));

-- ─── activity_entries ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "activity_entries" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "workflow_run_id" uuid REFERENCES "workflow_runs"(id) ON DELETE SET NULL,
    "workflow_id" uuid REFERENCES "workflows"(id) ON DELETE SET NULL,
    "thread_id" uuid REFERENCES "threads"(id) ON DELETE SET NULL,
    "agent_context" text,
    "action_type" text NOT NULL,
    "action_summary" text NOT NULL,
    "result" text NOT NULL,
    "result_details" text,
    "automation_level" text,
    "before_state" jsonb,
    "after_state" jsonb,
    "reasoning_chain_url" text,
    "reasoning_chain" jsonb,
    "target_type" text,
    "target_id" text,
    "step_id" text,
    "is_revertable" boolean NOT NULL DEFAULT true,
    "reverted_at" timestamp with time zone,
    "reverted_by_entry_id" uuid REFERENCES "activity_entries"(id),
    "occurred_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "activity_entries" ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS "idx_activity_user_time" ON "activity_entries" USING btree ("user_id", "occurred_at" DESC);
CREATE INDEX IF NOT EXISTS "idx_activity_workflow" ON "activity_entries" USING btree ("workflow_id", "occurred_at" DESC);
CREATE INDEX IF NOT EXISTS "idx_activity_target" ON "activity_entries" USING btree ("target_type", "target_id");

-- Idempotency constraint (WF-06): prevent duplicate activity entries on Inngest retry.
-- Partial: only enforced when both workflow_run_id AND step_id are non-null.
CREATE UNIQUE INDEX IF NOT EXISTS "activity_entries_run_step_unique"
    ON "activity_entries" ("workflow_run_id", "step_id")
    WHERE workflow_run_id IS NOT NULL AND step_id IS NOT NULL;

CREATE POLICY "activity_entries_user_policy" ON "activity_entries"
    AS PERMISSIVE FOR ALL TO "authenticated"
    USING ((SELECT auth.uid()) = "activity_entries"."user_id")
    WITH CHECK ((SELECT auth.uid()) = "activity_entries"."user_id");

-- ─── memory_items ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "memory_items" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "category" text NOT NULL,
    "content" text NOT NULL,
    "source_type" text,
    "source_reference_id" uuid,
    "confidence" real,
    "soft_deleted_at" timestamp with time zone,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "memory_items" ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS "idx_memory_user_category" ON "memory_items" USING btree ("user_id", "category") WHERE soft_deleted_at IS NULL;

CREATE POLICY "memory_items_user_policy" ON "memory_items"
    AS PERMISSIVE FOR ALL TO "authenticated"
    USING ((SELECT auth.uid()) = "memory_items"."user_id")
    WITH CHECK ((SELECT auth.uid()) = "memory_items"."user_id");

CREATE TRIGGER memory_items_updated_at
    BEFORE UPDATE ON "memory_items"
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ─── memory_embeddings (pgvector) ─────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "memory_embeddings" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "source_type" text NOT NULL,
    "source_id" uuid NOT NULL,
    "content" text NOT NULL,
    "embedding" vector(1024),
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "memory_embeddings" ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS "idx_memory_embeddings_user_id" ON "memory_embeddings" USING btree ("user_id");

-- HNSW index for approximate cosine similarity search (m=16, ef_construction=64)
CREATE INDEX IF NOT EXISTS "idx_memory_embeddings_hnsw" ON "memory_embeddings"
    USING hnsw ("embedding" vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

CREATE POLICY "memory_embeddings_user_policy" ON "memory_embeddings"
    AS PERMISSIVE FOR ALL TO "authenticated"
    USING ((SELECT auth.uid()) = "memory_embeddings"."user_id")
    WITH CHECK ((SELECT auth.uid()) = "memory_embeddings"."user_id");

-- ─── brand_voice_profiles ─────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "brand_voice_profiles" (
    "user_id" uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    "profile_markdown" text NOT NULL,
    "tone_tags" text[] DEFAULT '{}',
    "forbidden_phrases" text[] DEFAULT '{}',
    "example_url" text,
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "brand_voice_profiles" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "brand_voice_profiles_user_policy" ON "brand_voice_profiles"
    AS PERMISSIVE FOR ALL TO "authenticated"
    USING ((SELECT auth.uid()) = "brand_voice_profiles"."user_id")
    WITH CHECK ((SELECT auth.uid()) = "brand_voice_profiles"."user_id");

CREATE TRIGGER brand_voice_profiles_updated_at
    BEFORE UPDATE ON "brand_voice_profiles"
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ─── brand_voice_samples (pgvector) ───────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "brand_voice_samples" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "sample_text" text NOT NULL,
    "embedding" vector(1024),
    "source" text,
    "created_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "brand_voice_samples" ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS "idx_brand_voice_samples_user_id" ON "brand_voice_samples" USING btree ("user_id");

-- HNSW index for brand voice cosine similarity search
CREATE INDEX IF NOT EXISTS "idx_brand_voice_samples_hnsw" ON "brand_voice_samples"
    USING hnsw ("embedding" vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

CREATE POLICY "brand_voice_samples_user_policy" ON "brand_voice_samples"
    AS PERMISSIVE FOR ALL TO "authenticated"
    USING ((SELECT auth.uid()) = "brand_voice_samples"."user_id")
    WITH CHECK ((SELECT auth.uid()) = "brand_voice_samples"."user_id");

-- ─── autonomy_thresholds ──────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "autonomy_thresholds" (
    "user_id" uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    "default_level" text NOT NULL DEFAULT 'L2',
    "per_action_overrides" jsonb NOT NULL DEFAULT '{}',
    "updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "autonomy_thresholds" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "autonomy_thresholds_user_policy" ON "autonomy_thresholds"
    AS PERMISSIVE FOR ALL TO "authenticated"
    USING ((SELECT auth.uid()) = "autonomy_thresholds"."user_id")
    WITH CHECK ((SELECT auth.uid()) = "autonomy_thresholds"."user_id");

CREATE TRIGGER autonomy_thresholds_updated_at
    BEFORE UPDATE ON "autonomy_thresholds"
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ─── shopify_products ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "shopify_products" (
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "product_gid" text NOT NULL,
    "title" text,
    "body_html" text,
    "vendor" text,
    "product_type" text,
    "status" text,
    "tags" text[],
    "meta_title" text,
    "meta_description" text,
    "shopify_created_at" timestamp with time zone,
    "shopify_updated_at" timestamp with time zone,
    "last_synced_at" timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY ("user_id", "product_gid")
);

ALTER TABLE "shopify_products" ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS "idx_shopify_products_user" ON "shopify_products" USING btree ("user_id");
CREATE INDEX IF NOT EXISTS "idx_shopify_products_updated" ON "shopify_products" USING btree ("user_id", "shopify_updated_at" DESC);

CREATE POLICY "shopify_products_user_policy" ON "shopify_products"
    AS PERMISSIVE FOR ALL TO "authenticated"
    USING ((SELECT auth.uid()) = "shopify_products"."user_id")
    WITH CHECK ((SELECT auth.uid()) = "shopify_products"."user_id");

-- ─── shopify_product_variants ─────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "shopify_product_variants" (
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "variant_gid" text NOT NULL,
    "product_gid" text NOT NULL,
    "sku" text,
    "price" numeric(10, 2),
    "inventory_qty" integer,
    "last_synced_at" timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY ("user_id", "variant_gid")
);

ALTER TABLE "shopify_product_variants" ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS "idx_shopify_variants_user" ON "shopify_product_variants" USING btree ("user_id");

CREATE POLICY "shopify_product_variants_user_policy" ON "shopify_product_variants"
    AS PERMISSIVE FOR ALL TO "authenticated"
    USING ((SELECT auth.uid()) = "shopify_product_variants"."user_id")
    WITH CHECK ((SELECT auth.uid()) = "shopify_product_variants"."user_id");

-- ─── shopify_orders ───────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "shopify_orders" (
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "order_gid" text NOT NULL,
    "total" numeric(10, 2),
    "financial_status" text,
    "fulfillment_status" text,
    "shopify_created_at" timestamp with time zone,
    "last_synced_at" timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY ("user_id", "order_gid")
);

ALTER TABLE "shopify_orders" ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS "idx_shopify_orders_user" ON "shopify_orders" USING btree ("user_id");

CREATE POLICY "shopify_orders_user_policy" ON "shopify_orders"
    AS PERMISSIVE FOR ALL TO "authenticated"
    USING ((SELECT auth.uid()) = "shopify_orders"."user_id")
    WITH CHECK ((SELECT auth.uid()) = "shopify_orders"."user_id");

-- ─── shopify_pages ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "shopify_pages" (
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "page_gid" text NOT NULL,
    "title" text,
    "body_html" text,
    "handle" text,
    "last_synced_at" timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY ("user_id", "page_gid")
);

ALTER TABLE "shopify_pages" ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS "idx_shopify_pages_user" ON "shopify_pages" USING btree ("user_id");

CREATE POLICY "shopify_pages_user_policy" ON "shopify_pages"
    AS PERMISSIVE FOR ALL TO "authenticated"
    USING ((SELECT auth.uid()) = "shopify_pages"."user_id")
    WITH CHECK ((SELECT auth.uid()) = "shopify_pages"."user_id");

-- ─── shopify_redirects ────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "shopify_redirects" (
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "redirect_id" text NOT NULL,
    "path" text,
    "target" text,
    "last_synced_at" timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY ("user_id", "redirect_id")
);

ALTER TABLE "shopify_redirects" ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS "idx_shopify_redirects_user" ON "shopify_redirects" USING btree ("user_id");

CREATE POLICY "shopify_redirects_user_policy" ON "shopify_redirects"
    AS PERMISSIVE FOR ALL TO "authenticated"
    USING ((SELECT auth.uid()) = "shopify_redirects"."user_id")
    WITH CHECK ((SELECT auth.uid()) = "shopify_redirects"."user_id");

-- ─── shopify_sync_state ───────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "shopify_sync_state" (
    "user_id" uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    "last_full_sync_at" timestamp with time zone,
    "last_webhook_at" timestamp with time zone,
    "last_poll_at" timestamp with time zone,
    "sync_status" text,
    "webhook_subscriptions" jsonb
);

ALTER TABLE "shopify_sync_state" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "shopify_sync_state_user_policy" ON "shopify_sync_state"
    AS PERMISSIVE FOR ALL TO "authenticated"
    USING ((SELECT auth.uid()) = "shopify_sync_state"."user_id")
    WITH CHECK ((SELECT auth.uid()) = "shopify_sync_state"."user_id");

-- ─── gmail_threads ────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "gmail_threads" (
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "gmail_thread_id" text NOT NULL,
    "subject" text,
    "participants" text[],
    "is_customer_support" boolean DEFAULT false,
    "last_message_at" timestamp with time zone,
    "message_count" integer,
    "last_synced_at" timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY ("user_id", "gmail_thread_id")
);

ALTER TABLE "gmail_threads" ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS "idx_gmail_threads_user" ON "gmail_threads" USING btree ("user_id");

CREATE POLICY "gmail_threads_user_policy" ON "gmail_threads"
    AS PERMISSIVE FOR ALL TO "authenticated"
    USING ((SELECT auth.uid()) = "gmail_threads"."user_id")
    WITH CHECK ((SELECT auth.uid()) = "gmail_threads"."user_id");

-- ─── gmail_messages ───────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "gmail_messages" (
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "gmail_message_id" text NOT NULL,
    "gmail_thread_id" text NOT NULL,
    "from_address" text,
    "to_addresses" text[],
    "subject" text,
    "body_text" text,
    "body_html" text,
    "direction" text,
    "gmail_received_at" timestamp with time zone,
    "last_synced_at" timestamp with time zone DEFAULT now() NOT NULL,
    PRIMARY KEY ("user_id", "gmail_message_id")
);

ALTER TABLE "gmail_messages" ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS "idx_gmail_messages_user" ON "gmail_messages" USING btree ("user_id");
CREATE INDEX IF NOT EXISTS "idx_gmail_messages_thread" ON "gmail_messages" USING btree ("user_id", "gmail_thread_id");

CREATE POLICY "gmail_messages_user_policy" ON "gmail_messages"
    AS PERMISSIVE FOR ALL TO "authenticated"
    USING ((SELECT auth.uid()) = "gmail_messages"."user_id")
    WITH CHECK ((SELECT auth.uid()) = "gmail_messages"."user_id");

-- ─── gmail_sync_state ─────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "gmail_sync_state" (
    "user_id" uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    "last_history_id" text,
    "last_poll_at" timestamp with time zone,
    "sync_status" text
);

ALTER TABLE "gmail_sync_state" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "gmail_sync_state_user_policy" ON "gmail_sync_state"
    AS PERMISSIVE FOR ALL TO "authenticated"
    USING ((SELECT auth.uid()) = "gmail_sync_state"."user_id")
    WITH CHECK ((SELECT auth.uid()) = "gmail_sync_state"."user_id");

-- ─── agent_telemetry ──────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "agent_telemetry" (
    "id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "call_type" text NOT NULL,
    "workflow_run_id" uuid REFERENCES "workflow_runs"(id),
    "thread_id" uuid REFERENCES "threads"(id),
    "message_id" uuid REFERENCES "messages"(id),
    "model_id" text NOT NULL,
    "prompt_tokens" integer NOT NULL,
    "completion_tokens" integer NOT NULL,
    "total_tokens" integer NOT NULL,
    "cost_usd" numeric(10, 6),
    "latency_ms" integer NOT NULL,
    "success" boolean NOT NULL,
    "error_class" text,
    "tools_invoked" text[],
    "occurred_at" timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE "agent_telemetry" ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS "idx_telemetry_user_time" ON "agent_telemetry" USING btree ("user_id", "occurred_at" DESC);

CREATE POLICY "agent_telemetry_user_policy" ON "agent_telemetry"
    AS PERMISSIVE FOR ALL TO "authenticated"
    USING ((SELECT auth.uid()) = "agent_telemetry"."user_id")
    WITH CHECK ((SELECT auth.uid()) = "agent_telemetry"."user_id");

-- ─── cost_aggregates ──────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS "cost_aggregates" (
    "user_id" uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    "day" date NOT NULL,
    "total_tokens" bigint NOT NULL DEFAULT 0,
    "total_cost_usd" numeric(10, 4) NOT NULL DEFAULT 0,
    "llm_calls" integer NOT NULL DEFAULT 0,
    "workflow_runs" integer NOT NULL DEFAULT 0,
    PRIMARY KEY ("user_id", "day")
);

ALTER TABLE "cost_aggregates" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "cost_aggregates_user_policy" ON "cost_aggregates"
    AS PERMISSIVE FOR ALL TO "authenticated"
    USING ((SELECT auth.uid()) = "cost_aggregates"."user_id")
    WITH CHECK ((SELECT auth.uid()) = "cost_aggregates"."user_id");

-- ─── ALTER TABLE user_profiles: add onboarding_step ──────────────────────────
-- Forward-only: adds column to existing table (created in 0001).
-- onboarding_step tracks progress for ONBOARD-06 (abandoned onboarding resume).

ALTER TABLE "user_profiles"
    ADD COLUMN IF NOT EXISTS "onboarding_step" integer DEFAULT 0;
